server:
  port: 8090
  servlet:
    context-path: "/Customer-Service"
spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
#  springdoc:
#    api-docs:
#      path: /api-docs
#    swagger-ui:
#      path: /swagger-ui.html
#      operationsSorter: method