spring:
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9098/realms/e-commerce
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/v1/customer/**
          filters:
            - name: RewritePath
              args:
                regexp: /api/v1/customer/(?<segment>.*)
                replacement: /api/v1/$\{segment}


        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**


        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**


server:
  port: 8222
eureka:
  client:
    service-url:
      defaultZone : //localhost:8761/eureka/
  instance:
    prefer-ip-address: true